# Generated by Django 3.2 on 2021-05-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('ans_idx', models.AutoField(primary_key=True, serialize=False)),
                ('surv_idx', models.IntegerField()),
                ('ans', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Surv',
            fields=[
                ('surv_idx', models.AutoField(primary_key=True, serialize=False)),
                ('questoin', models.TextField()),
                ('ans1', models.TextField()),
                ('ans2', models.TextField()),
                ('ans3', models.TextField()),
                ('valid', models.CharField(default='y', max_length=1)),
            ],
        ),
    ]
