# Generated by Django 3.2 on 2021-05-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surv',
            old_name='questoin',
            new_name='question',
        ),
    ]
